import type { AdminTask, DeliveryTask, MerchantOrder, StoreSummary } from './types'

export const categories = ['全部', '炸鸡汉堡', '米饭套餐', '奶茶咖啡', '日韩料理', '夜宵烧烤']

export const stores: StoreSummary[] = [
  {
    id: 'store-koala-bowl',
    name: '考拉能量饭',
    category: '米饭套餐',
    rating: 4.8,
    monthlySales: 1320,
    deliveryMinutes: 28,
    deliveryFee: 2.99,
    distanceKm: 1.4,
    promotion: '满 $35 减 $6',
    coverTone: 'rice',
    menu: [
      {
        id: 'bowl-teriyaki',
        name: '照烧鸡腿饭',
        description: '去骨鸡腿、溏心蛋、时蔬、秘制照烧汁',
        price: 16.8,
        monthlySales: 420,
        tag: '招牌',
      },
      {
        id: 'bowl-beef',
        name: '黑椒牛肉饭',
        description: '嫩牛肉片、洋葱、青椒、黑椒酱',
        price: 18.5,
        monthlySales: 316,
        tag: '热卖',
      },
      {
        id: 'bowl-veggie',
        name: '南瓜素食饭',
        description: '烤南瓜、豆腐、玉米、芝麻酱',
        price: 14.2,
        monthlySales: 128,
        tag: '轻食',
      },
    ],
  },
  {
    id: 'store-burger',
    name: '金袋汉堡',
    category: '炸鸡汉堡',
    rating: 4.7,
    monthlySales: 2210,
    deliveryMinutes: 24,
    deliveryFee: 1.99,
    distanceKm: 0.9,
    promotion: '第二份半价',
    coverTone: 'burger',
    menu: [
      {
        id: 'burger-classic',
        name: '双层芝士牛堡',
        description: '双层牛肉饼、车达芝士、酸黄瓜',
        price: 15.9,
        monthlySales: 760,
        tag: '爆款',
      },
      {
        id: 'burger-chicken',
        name: '脆皮鸡腿堡',
        description: '整块鸡腿排、生菜、蜂蜜芥末酱',
        price: 13.8,
        monthlySales: 540,
        tag: '人气',
      },
      {
        id: 'fries-combo',
        name: '薯条可乐套餐',
        description: '大份薯条、无糖可乐、蒜香蘸酱',
        price: 8.8,
        monthlySales: 690,
        tag: '套餐',
      },
    ],
  },
  {
    id: 'store-milk-tea',
    name: '黄罐奶茶',
    category: '奶茶咖啡',
    rating: 4.9,
    monthlySales: 1880,
    deliveryMinutes: 18,
    deliveryFee: 0.99,
    distanceKm: 0.6,
    promotion: '新品立减 $2',
    coverTone: 'tea',
    menu: [
      {
        id: 'tea-boba',
        name: '黑糖珍珠鲜奶',
        description: '黑糖珍珠、鲜奶、轻冰默认',
        price: 7.6,
        monthlySales: 880,
        tag: '必点',
      },
      {
        id: 'tea-lemon',
        name: '鸭屎香柠檬茶',
        description: '现捣香水柠檬、凤凰单丛茶底',
        price: 7.2,
        monthlySales: 520,
        tag: '清爽',
      },
      {
        id: 'coffee-latte',
        name: '燕麦拿铁',
        description: '双份浓缩、燕麦奶、少糖',
        price: 6.9,
        monthlySales: 260,
        tag: '咖啡',
      },
    ],
  },
  {
    id: 'store-sushi',
    name: '海港寿司',
    category: '日韩料理',
    rating: 4.6,
    monthlySales: 980,
    deliveryMinutes: 32,
    deliveryFee: 3.49,
    distanceKm: 2.1,
    promotion: '套餐免配送费',
    coverTone: 'sushi',
    menu: [
      {
        id: 'sushi-salmon',
        name: '三文鱼寿司盒',
        description: '三文鱼握寿司、卷物、芥末酱油',
        price: 21.8,
        monthlySales: 230,
        tag: '鲜切',
      },
      {
        id: 'sushi-chicken',
        name: '照烧鸡便当',
        description: '鸡腿肉、米饭、沙拉、玉子烧',
        price: 17.6,
        monthlySales: 190,
        tag: '便当',
      },
      {
        id: 'miso-soup',
        name: '味噌汤',
        description: '海带、豆腐、葱花',
        price: 4.2,
        monthlySales: 310,
        tag: '配餐',
      },
    ],
  },
]

export const merchantOrders: MerchantOrder[] = [
  {
    id: 'KE-2048',
    customerName: 'Shuaijie',
    itemsSummary: '照烧鸡腿饭 x2、味噌汤 x1',
    status: '待接单',
    totalAmount: 37.8,
    placedMinutesAgo: 3,
  },
  {
    id: 'KE-2049',
    customerName: 'Mia',
    itemsSummary: '双层芝士牛堡 x1、薯条可乐套餐 x1',
    status: '备餐中',
    totalAmount: 24.7,
    placedMinutesAgo: 9,
  },
  {
    id: 'KE-2050',
    customerName: 'Noah',
    itemsSummary: '黑糖珍珠鲜奶 x3',
    status: '待出餐',
    totalAmount: 22.8,
    placedMinutesAgo: 14,
  },
]

export const deliveryTasks: DeliveryTask[] = [
  {
    id: 'D-801',
    storeName: '考拉能量饭',
    customerAddress: '12 Queen Street',
    distanceKm: 2.8,
    fee: 8.5,
    status: '可接单',
  },
  {
    id: 'D-802',
    storeName: '金袋汉堡',
    customerAddress: '88 Hobson Street',
    distanceKm: 1.7,
    fee: 6.2,
    status: '配送中',
  },
  {
    id: 'D-803',
    storeName: '黄罐奶茶',
    customerAddress: '36 Wakefield Street',
    distanceKm: 1.2,
    fee: 5.8,
    status: '取餐中',
  },
]

export const adminTasks: AdminTask[] = [
  {
    id: 'A-301',
    title: '新商家资质审核',
    owner: '海港寿司',
    status: '待审核',
    severity: 'warning',
  },
  {
    id: 'A-302',
    title: '订单配送异常',
    owner: 'KE-2047',
    status: '待处理',
    severity: 'urgent',
  },
  {
    id: 'A-303',
    title: '骑手账号认证',
    owner: 'Rider #18',
    status: '待复核',
    severity: 'normal',
  },
]
