import type {
  AccountRecord,
  AdminTask,
  Coupon,
  CustomerAddress,
  CustomerOrder,
  DeliveryArea,
  DeliveryTask,
  MerchantApplication,
  MerchantMenuItem,
  MerchantOrder,
  MerchantStoreProfile,
  MockBusinessState,
  PlatformOrder,
  StoreSummary,
} from './types'

export const categories = ['全部', '炸鸡汉堡', '米饭套餐', '奶茶咖啡', '日韩料理', '夜宵烧烤']

export const customerAddresses: CustomerAddress[] = [
  {
    id: 'address-home',
    label: '家',
    receiverName: 'Shuaijie',
    phoneMasked: '021 **** 118',
    addressLine: '12 Queen Street, Auckland CBD',
    detail: 'Apartment 8B',
    coordinates: { latitude: -36.8489, longitude: 174.7633 },
  },
  {
    id: 'address-school',
    label: '学校',
    receiverName: 'Shuaijie',
    phoneMasked: '021 **** 118',
    addressLine: '55 Wellesley Street East',
    detail: 'Main entrance',
    coordinates: { latitude: -36.8537, longitude: 174.7671 },
  },
]

export const coupons: Coupon[] = [
  {
    id: 'coupon-35-6',
    title: '满 $35 减 $6',
    thresholdAmount: 35,
    discountAmount: 6,
  },
  {
    id: 'coupon-25-3',
    title: '满 $25 减 $3',
    thresholdAmount: 25,
    discountAmount: 3,
  },
]

export const stores: StoreSummary[] = [
  {
    id: 'store-koala-bowl',
    name: '考拉能量饭',
    category: '米饭套餐',
    rating: 4.8,
    monthlySales: 1320,
    deliveryMinutes: 28,
    deliveryFee: 2.99,
    distanceKm: 1.4,
    promotion: '满 $35 减 $6',
    coverTone: 'rice',
    address: '18 Queen Street, Auckland CBD',
    openingHours: '10:30 - 21:30',
    announcement: '午高峰预计出餐 12 分钟，支持少盐少油备注。',
    minOrderAmount: 15,
    averagePrice: 19,
    deliveryRadiusKm: 4.5,
    serviceTags: ['准时宝', '商家自配', '支持备注'],
    location: { latitude: -36.8478, longitude: 174.765 },
    menuCategories: [
      { id: 'signature', name: '招牌套餐' },
      { id: 'light', name: '轻食热卖' },
      { id: 'side', name: '小食饮品' },
    ],
    menu: [
      {
        id: 'bowl-teriyaki',
        categoryId: 'signature',
        name: '照烧鸡腿饭',
        description: '去骨鸡腿、溏心蛋、时蔬、秘制照烧汁',
        price: 16.8,
        monthlySales: 420,
        tag: '招牌',
        stock: 38,
        isAvailable: true,
        imageTone: 'rice',
        optionGroups: [
          {
            id: 'rice-size',
            name: '米饭份量',
            required: true,
            options: [
              { id: 'regular', name: '标准饭量', priceDelta: 0 },
              { id: 'large', name: '加饭', priceDelta: 1.5 },
            ],
          },
          {
            id: 'flavor',
            name: '口味',
            required: true,
            options: [
              { id: 'normal', name: '正常', priceDelta: 0 },
              { id: 'less-salt', name: '少盐', priceDelta: 0 },
            ],
          },
        ],
      },
      {
        id: 'bowl-beef',
        categoryId: 'signature',
        name: '黑椒牛肉饭',
        description: '嫩牛肉片、洋葱、青椒、黑椒酱',
        price: 18.5,
        monthlySales: 316,
        tag: '热卖',
        stock: 26,
        isAvailable: true,
        imageTone: 'rice',
      },
      {
        id: 'bowl-veggie',
        categoryId: 'light',
        name: '南瓜素食饭',
        description: '烤南瓜、豆腐、玉米、芝麻酱',
        price: 14.2,
        monthlySales: 128,
        tag: '轻食',
        stock: 12,
        isAvailable: true,
        imageTone: 'tea',
      },
      {
        id: 'miso-soup',
        categoryId: 'side',
        name: '味噌汤',
        description: '海带、豆腐、葱花',
        price: 4.2,
        monthlySales: 310,
        tag: '配餐',
        stock: 80,
        isAvailable: true,
        imageTone: 'sushi',
      },
    ],
  },
  {
    id: 'store-burger',
    name: '金袋汉堡',
    category: '炸鸡汉堡',
    rating: 4.7,
    monthlySales: 2210,
    deliveryMinutes: 24,
    deliveryFee: 1.99,
    distanceKm: 0.9,
    promotion: '第二份半价',
    coverTone: 'burger',
    address: '68 Hobson Street, Auckland CBD',
    openingHours: '09:30 - 23:00',
    announcement: '炸鸡现点现炸，晚高峰建议提前下单。',
    minOrderAmount: 12,
    averagePrice: 17,
    deliveryRadiusKm: 5,
    serviceTags: ['快速出餐', '夜宵', '平台配送'],
    location: { latitude: -36.8496, longitude: 174.7585 },
    menuCategories: [
      { id: 'burger-main', name: '汉堡' },
      { id: 'fried', name: '炸物' },
      { id: 'combo', name: '套餐' },
    ],
    menu: [
      {
        id: 'burger-classic',
        categoryId: 'burger-main',
        name: '双层芝士牛堡',
        description: '双层牛肉饼、车达芝士、酸黄瓜',
        price: 15.9,
        monthlySales: 760,
        tag: '爆款',
        stock: 44,
        isAvailable: true,
        imageTone: 'burger',
      },
      {
        id: 'burger-chicken',
        categoryId: 'burger-main',
        name: '脆皮鸡腿堡',
        description: '整块鸡腿排、生菜、蜂蜜芥末酱',
        price: 13.8,
        monthlySales: 540,
        tag: '人气',
        stock: 31,
        isAvailable: true,
        imageTone: 'burger',
      },
      {
        id: 'fries-combo',
        categoryId: 'combo',
        name: '薯条可乐套餐',
        description: '大份薯条、无糖可乐、蒜香蘸酱',
        price: 8.8,
        monthlySales: 690,
        tag: '套餐',
        stock: 52,
        isAvailable: true,
        imageTone: 'burger',
      },
    ],
  },
  {
    id: 'store-milk-tea',
    name: '黄罐奶茶',
    category: '奶茶咖啡',
    rating: 4.9,
    monthlySales: 1880,
    deliveryMinutes: 18,
    deliveryFee: 0.99,
    distanceKm: 0.6,
    promotion: '新品立减 $2',
    coverTone: 'tea',
    address: '36 Wakefield Street, Auckland CBD',
    openingHours: '11:00 - 22:30',
    announcement: '默认少冰少糖，可在备注中调整甜度。',
    minOrderAmount: 10,
    averagePrice: 9,
    deliveryRadiusKm: 3.5,
    serviceTags: ['可调甜度', '可调冰量', '极速达'],
    location: { latitude: -36.8531, longitude: 174.7644 },
    menuCategories: [
      { id: 'milk', name: '鲜奶茶' },
      { id: 'fruit', name: '果茶' },
      { id: 'coffee', name: '咖啡' },
    ],
    menu: [
      {
        id: 'tea-boba',
        categoryId: 'milk',
        name: '黑糖珍珠鲜奶',
        description: '黑糖珍珠、鲜奶、轻冰默认',
        price: 7.6,
        monthlySales: 880,
        tag: '必点',
        stock: 96,
        isAvailable: true,
        imageTone: 'tea',
        optionGroups: [
          {
            id: 'sweetness',
            name: '甜度',
            required: true,
            options: [
              { id: 'less-sugar', name: '少糖', priceDelta: 0 },
              { id: 'half-sugar', name: '半糖', priceDelta: 0 },
              { id: 'full-sugar', name: '全糖', priceDelta: 0 },
            ],
          },
          {
            id: 'ice',
            name: '冰量',
            required: true,
            options: [
              { id: 'less-ice', name: '少冰', priceDelta: 0 },
              { id: 'no-ice', name: '去冰', priceDelta: 0 },
            ],
          },
          {
            id: 'topping',
            name: '加料',
            required: true,
            options: [
              { id: 'none', name: '不加料', priceDelta: 0 },
              { id: 'extra-boba', name: '加珍珠', priceDelta: 0.8 },
              { id: 'cheese-foam', name: '芝士奶盖', priceDelta: 1.2 },
            ],
          },
        ],
      },
      {
        id: 'tea-lemon',
        categoryId: 'fruit',
        name: '鸭屎香柠檬茶',
        description: '现捣香水柠檬、凤凰单丛茶底',
        price: 7.2,
        monthlySales: 520,
        tag: '清爽',
        stock: 60,
        isAvailable: true,
        imageTone: 'tea',
      },
      {
        id: 'coffee-latte',
        categoryId: 'coffee',
        name: '燕麦拿铁',
        description: '双份浓缩、燕麦奶、少糖',
        price: 6.9,
        monthlySales: 260,
        tag: '咖啡',
        stock: 40,
        isAvailable: true,
        imageTone: 'tea',
      },
    ],
  },
  {
    id: 'store-sushi',
    name: '海港寿司',
    category: '日韩料理',
    rating: 4.6,
    monthlySales: 980,
    deliveryMinutes: 32,
    deliveryFee: 3.49,
    distanceKm: 2.1,
    promotion: '套餐免配送费',
    coverTone: 'sushi',
    address: '9 Customs Street East, Auckland CBD',
    openingHours: '10:00 - 20:30',
    announcement: '刺身类售完即止，建议优先选择套餐。',
    minOrderAmount: 18,
    averagePrice: 24,
    deliveryRadiusKm: 4,
    serviceTags: ['新鲜现切', '支持预约', '保温配送'],
    location: { latitude: -36.8442, longitude: 174.7678 },
    menuCategories: [
      { id: 'sushi-box', name: '寿司盒' },
      { id: 'bento', name: '便当' },
      { id: 'soup', name: '汤品' },
    ],
    menu: [
      {
        id: 'sushi-salmon',
        categoryId: 'sushi-box',
        name: '三文鱼寿司盒',
        description: '三文鱼握寿司、卷物、芥末酱油',
        price: 21.8,
        monthlySales: 230,
        tag: '鲜切',
        stock: 18,
        isAvailable: true,
        imageTone: 'sushi',
      },
      {
        id: 'sushi-chicken',
        categoryId: 'bento',
        name: '照烧鸡便当',
        description: '鸡腿肉、米饭、沙拉、玉子烧',
        price: 17.6,
        monthlySales: 190,
        tag: '便当',
        stock: 21,
        isAvailable: true,
        imageTone: 'rice',
      },
      {
        id: 'sushi-miso',
        categoryId: 'soup',
        name: '海带味噌汤',
        description: '海带、豆腐、葱花',
        price: 4.2,
        monthlySales: 310,
        tag: '配餐',
        stock: 36,
        isAvailable: true,
        imageTone: 'sushi',
      },
    ],
  },
]

export const merchantProfile: MerchantStoreProfile = {
  id: 'store-koala-bowl',
  name: '考拉能量饭',
  address: '18 Queen Street, Auckland CBD',
  openingHours: '10:30 - 21:30',
  isOpen: true,
  deliveryRadiusKm: 4.5,
  averagePreparationMinutes: 12,
  announcement: '午高峰预计出餐 12 分钟，支持少盐少油备注。',
  coordinates: { latitude: -36.8478, longitude: 174.765 },
}

export const merchantOrders: MerchantOrder[] = [
  {
    id: 'KE-2048',
    customerName: 'Shuaijie',
    itemsSummary: '照烧鸡腿饭 x2、味噌汤 x1',
    items: [
      { ...stores[0].menu[0], cartKey: 'bowl-teriyaki', quantity: 2 },
      { ...stores[0].menu[3], cartKey: 'miso-soup', quantity: 1 },
    ],
    status: 'PendingAccept',
    statusText: '待接单',
    totalAmount: 37.8,
    placedMinutesAgo: 3,
    deliveryAddressMasked: 'Queen Street 附近',
    customerNote: '少盐，不要葱，门口电话联系。',
    paymentStatus: 'Paid',
  },
  {
    id: 'KE-2049',
    customerName: 'Mia',
    itemsSummary: '黑椒牛肉饭 x1、南瓜素食饭 x1',
    items: [
      { ...stores[0].menu[1], cartKey: 'bowl-beef', quantity: 1 },
      { ...stores[0].menu[2], cartKey: 'bowl-veggie', quantity: 1 },
    ],
    status: 'Preparing',
    statusText: '备餐中',
    totalAmount: 35.1,
    placedMinutesAgo: 9,
    deliveryAddressMasked: 'Hobson Street 附近',
    customerNote: '餐具 2 份。',
    paymentStatus: 'Paid',
  },
  {
    id: 'KE-2050',
    customerName: 'Noah',
    itemsSummary: '照烧鸡腿饭 x1',
    items: [{ ...stores[0].menu[0], cartKey: 'bowl-teriyaki', quantity: 1 }],
    status: 'ReadyForPickup',
    statusText: '待骑手取餐',
    totalAmount: 20.19,
    placedMinutesAgo: 14,
    deliveryAddressMasked: 'Wakefield Street 附近',
    customerNote: '放前台。',
    paymentStatus: 'Paid',
  },
]

export const merchantMenuItems: MerchantMenuItem[] = stores[0].menu.map((item) => ({
  ...item,
  categoryName: stores[0].menuCategories.find((category) => category.id === item.categoryId)?.name ?? '未分类',
}))

export const deliveryTasks: DeliveryTask[] = [
  {
    id: 'D-801',
    orderId: 'KE-2050',
    storeName: '考拉能量饭',
    pickupAddress: '18 Queen Street, Auckland CBD',
    customerAddress: '12 Queen Street, Auckland CBD',
    distanceKm: 2.8,
    fee: 8.5,
    status: 'Available',
    statusText: '可接单',
    pickupCode: '7421',
    customerPhoneMasked: '021 **** 118',
    estimatedMinutes: 24,
    pickupLocation: { latitude: -36.8478, longitude: 174.765 },
    dropoffLocation: { latitude: -36.8489, longitude: 174.7633 },
  },
  {
    id: 'D-802',
    orderId: 'KE-2046',
    storeName: '金袋汉堡',
    pickupAddress: '68 Hobson Street',
    customerAddress: '88 Hobson Street',
    distanceKm: 1.7,
    fee: 6.2,
    status: 'Delivering',
    statusText: '配送中',
    pickupCode: '5180',
    customerPhoneMasked: '022 **** 301',
    estimatedMinutes: 12,
    pickupLocation: { latitude: -36.8496, longitude: 174.7585 },
    dropoffLocation: { latitude: -36.852, longitude: 174.7592 },
  },
  {
    id: 'D-803',
    orderId: 'KE-2045',
    storeName: '黄罐奶茶',
    pickupAddress: '36 Wakefield Street',
    customerAddress: '55 Wellesley Street East',
    distanceKm: 1.2,
    fee: 5.8,
    status: 'PickedUp',
    statusText: '已取餐',
    pickupCode: '9302',
    customerPhoneMasked: '027 **** 645',
    estimatedMinutes: 9,
    pickupLocation: { latitude: -36.8531, longitude: 174.7644 },
    dropoffLocation: { latitude: -36.8537, longitude: 174.7671 },
  },
]

export const adminTasks: AdminTask[] = [
  {
    id: 'A-301',
    title: '新商家资质审核',
    owner: '海港寿司',
    status: '待审核',
    severity: 'warning',
  },
  {
    id: 'A-302',
    title: '订单配送异常',
    owner: 'KE-2047',
    status: '待处理',
    severity: 'urgent',
  },
  {
    id: 'A-303',
    title: '骑手账号认证',
    owner: 'Rider #18',
    status: '待复核',
    severity: 'normal',
  },
]

export const merchantApplications: MerchantApplication[] = [
  {
    id: 'MA-101',
    storeName: '海港寿司',
    applicantName: 'Haruto',
    category: '日韩料理',
    address: '9 Customs Street East',
    submittedHoursAgo: 5,
    status: 'Pending',
  },
  {
    id: 'MA-102',
    storeName: '湾区烧烤',
    applicantName: 'Chen',
    category: '夜宵烧烤',
    address: '22 Lorne Street',
    submittedHoursAgo: 13,
    status: 'Pending',
  },
]

export const platformOrders: PlatformOrder[] = [
  {
    id: 'KE-2047',
    storeName: '金袋汉堡',
    customerName: 'Mia',
    riderName: '未分配',
    status: '派单超时',
    totalAmount: 24.7,
    riskLevel: 'urgent',
  },
  {
    id: 'KE-2048',
    storeName: '考拉能量饭',
    customerName: 'Shuaijie',
    riderName: 'Liam',
    status: '商家待接单',
    totalAmount: 37.8,
    riskLevel: 'warning',
  },
  {
    id: 'KE-2049',
    storeName: '黄罐奶茶',
    customerName: 'Noah',
    riderName: 'Ava',
    status: '正常配送',
    totalAmount: 22.8,
    riskLevel: 'normal',
  },
]

export const accountRecords: AccountRecord[] = [
  { id: 'U-1001', name: 'Shuaijie', role: 'Customer', status: 'Active' },
  { id: 'M-2001', name: '考拉能量饭', role: 'Merchant', status: 'Active' },
  { id: 'R-3001', name: 'Liam', role: 'Rider', status: 'Active' },
  { id: 'R-3002', name: 'Rider #18', role: 'Rider', status: 'PendingReview' },
]

export const deliveryAreas: DeliveryArea[] = [
  { id: 'DA-1', name: 'Auckland CBD', radiusKm: 5, baseFee: 2.99, isEnabled: true },
  { id: 'DA-2', name: 'Newmarket', radiusKm: 4, baseFee: 3.49, isEnabled: true },
  { id: 'DA-3', name: 'Parnell', radiusKm: 3, baseFee: 3.99, isEnabled: false },
]

export const customerOrder: CustomerOrder = {
  id: 'KE-2048',
  storeId: 'store-koala-bowl',
  storeName: '考拉能量饭',
  status: 'Delivering',
  statusText: '骑手配送中',
  address: customerAddresses[0],
  items: [
    { ...stores[0].menu[0], cartKey: 'bowl-teriyaki', quantity: 2 },
    { ...stores[0].menu[3], cartKey: 'miso-soup', quantity: 1 },
  ],
  price: {
    itemsAmount: 37.8,
    deliveryFee: 2.99,
    packagingFee: 0.8,
    discountAmount: 6,
    totalAmount: 35.59,
  },
  riderName: 'Liam',
  riderPhoneMasked: '020 **** 776',
  riderLocation: { latitude: -36.8482, longitude: 174.764 },
  estimatedArrivalMinutes: 12,
  timeline: [
    {
      key: 'PendingPayment',
      label: '提交订单',
      description: '订单已提交，等待支付',
      happenedAt: '12:06',
      isCompleted: true,
    },
    {
      key: 'Paid',
      label: '支付成功',
      description: '模拟支付完成，商家已收到订单',
      happenedAt: '12:07',
      isCompleted: true,
    },
    {
      key: 'MerchantAccepted',
      label: '商家接单',
      description: '商家确认接单，开始准备',
      happenedAt: '12:09',
      isCompleted: true,
    },
    {
      key: 'RiderPickedUp',
      label: '骑手取餐',
      description: '骑手已取到餐品',
      happenedAt: '12:22',
      isCompleted: true,
    },
    {
      key: 'Delivering',
      label: '配送中',
      description: '预计 12 分钟送达',
      happenedAt: '现在',
      isCompleted: true,
    },
    {
      key: 'Completed',
      label: '已送达',
      description: '完成后可评价商家和骑手',
      happenedAt: '--',
      isCompleted: false,
    },
  ],
}

export const initialMockBusinessState: MockBusinessState = {
  customerOrders: [customerOrder],
  merchantOrders,
  merchantMenuItems,
  merchantProfile,
  deliveryTasks,
  merchantApplications,
  platformOrders,
  accountRecords,
  deliveryAreas,
}
