name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/server/KoalaEats.Api/KoalaEats.Api.csproj

      - name: Build
        run: dotnet build src/server/KoalaEats.Api/KoalaEats.Api.csproj --configuration Release --no-restore

  client:
    name: Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: src/client/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
